<?
/*
        Copyright (C) 2000-2002 Liquid Bytes (R), Germany. All rights reserved.
        http://www.liquidbytes.net/
 
        This file is part of the liquidbytes.net Adaptive Website Framework (AWF)
        The author is Michael Mayer (michael@liquidbytes.net)
        Last update: 23.06.2002
*/
?>

<table width="100%" cellpadding="0" cellspacing="0 border="0" bgcolor="#000000"><tr><td align="center">
<span class="lbfooter">&copy; 2000-2002 Liquid Bytes - 'Liquid Bytes' is a registered trademark of Liquid Bytes, Germany</span>
</td>
</tr>
</table>
