<?php
/*
        Copyright (C) 2000-2002 Liquid Bytes (R), Germany. All rights reserved.
        http://www.liquidbytes.net/
 
        This file is part of the liquidbytes.net Adaptive Website Framework (AWF)
        The author is Michael Mayer (michael@liquidbytes.net)
        Last update: 23.06.2002
*/

?>

<p style="text-align: center">
<img src="img/erdbeere4.gif" border="0"><br />
&copy; 2001 Strawberry Corp.
</p>


