<?php
/*
        Copyright (C) 2000-2001 Liquid Bytes (R), Germany. All rights reserved.
        http://www.liquidbytes.net/
 
        This file is part of the liquidbytes.net Adaptive Website Framework (AWF)
        The author is Michael Mayer (michael@liquidbytes.net)
        Last update: 31.12.2001
*/

define('TABLE_USERS', 		$db_table_prefix.'users');
define('TABLE_USERDATA', 	$db_table_prefix.'userdata');
define('TABLE_GROUPS', 		$db_table_prefix.'groups');
define('TABLE_GROUPDATA', 	$db_table_prefix.'groupdata');
define('TABLE_MESSAGES',	$db_table_prefix.'messages');
define('TABLE_FLAVOURS',	$db_table_prefix.'flavours');
define('TABLE_ADS', 		$db_table_prefix.'ads');
define('TABLE_MODULES', 	$db_table_prefix.'modules');
define('TABLE_NODES', 		$db_table_prefix.'nodes');
define('TABLE_NODEDATA', 	$db_table_prefix.'nodedata');
define('TABLE_POLLS', 		$db_table_prefix.'polls');
define('TABLE_POLLS_ITEMS', 	$db_table_prefix.'polls_items');
define('TABLE_REDIRECT', 	$db_table_prefix.'redirect');
define('TABLE_SETUP', 		$db_table_prefix.'setup');
define('TABLE_TYPES', 		$db_table_prefix.'types');
define('TABLE_TYPEDATA', 	$db_table_prefix.'typedata');

?>
