<?php
/*
        Copyright (C) 2000-2002 Liquid Bytes (R), Germany. All rights reserved.
        http://www.liquidbytes.net/

        This file is part of the liquidbytes.net Adaptive Website Framework (AWF)
        The author is Michael Mayer (michael@liquidbytes.net)
        Last update: 23.06.2002
*/
?>
<p style="text-align: center; font-family: arial, helvetica, sans serif, verdana; font-size: 13px">
<img src="img/error.gif" border="0" />
<br />
<span style="font-weight: bold">Don't panic!</span>
<br />
<br />
This page appears, because the connection to a required <?php echo(DBMS.' '); ?>database server can't be 
established. In most cases, the reason is incorrect account information. Please attempt your request again 
(if you are repeatedly unsuccessful you should notify the site administrator).
</p>
